service: basic-api-node

provider:
    name: aws
    runtime: nodejs20.x
    region: us-east-2
    stage: ${opt:stage, 'dev'}
    profile: crazy
    iamRoleStatements:
        - Effect: "Allow"
          Action:
           - logs:CreateLogStream
           - logs:CreateLogGroup
           - logs:PutLogEvents
          Resource: "*"
    apiGateway:
        binaryMediaTypes:
            - 'multipart/form-data'

functions:
    api:
        description: 'Basic API Express with Mongoose'
        name: basic-api-node-${opt:stage, 'dev'}
        handler: server.handler
        events:
            - httpApi: '*'
        vpc:
            securityGroupIds:
                - sg-6f714c14
            subnetIds:
                - subnet-b7b28bcd
                - subnet-b80161f4
